### 회원가입 (수강생)
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "mysqlstudent",
    "password": "mypassword123",
    "role": "student"
}

### 회원가입 (관리자)
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "mysqladmin",
    "password": "myadminpassword",
    "role": "admin"
}

### 로그인
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "mysqlstudent",
    "password": "mypassword123"
}

### 잘못된 로그인 시도
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "mysqlstudent",
    "password": "wrongpassword"
}